### ISSUE TITLE
Error in OAuth Server

### ISSUE THREAD

**Issue by denzils** [meteor/localmarket#9]
Hi, I'm running local market meteor --settings ../settings.json
and my settings.json file is exactly what's specified in the info section.

I'm getting the following error though (running on my mac osx sierra):
W20170114-01:19:41.355(-5) (oauth.js:428) Error in OAuth Server: Failed to send OAuth1 request to https://api.twitter.com/oauth/request_token. failed [401] {"errors":[{"code":32,"message":"Could not authenticate you."}]}
I20170114-01:19:42.183(-5)? Exception while invoking method 'login' Error: Failed to send OAuth1 request to https://api.twitter.com/oauth/request_token. failed [401] {"errors":[{"code":32,"message":"Could not authenticate you."}]}
I20170114-01:19:42.184(-5)?     at [object Object].OAuth1Binding._call (packages/oauth1.js:204:20)
I20170114-01:19:42.184(-5)?     at [object Object].OAuth1Binding.prepareRequestToken (packages/oauth1.js:57:23)
I20170114-01:19:42.184(-5)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth1.js:268:18)
I20170114-01:19:42.184(-5)?     at middleware (packages/oauth.js:203:5)
I20170114-01:19:42.184(-5)?     at packages/oauth.js:176:5

**Comment by yusef-ho** [comment]
same issues here
